# Generated by Django 2.1.3 on 2019-01-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'ordering': ['site_name']},
        ),
    ]
